# -*- coding: utf-8 -*-
"""ATIVIDADE 2-checkpoint.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V4tJIp-BBWzRG5SlBSKyg6892I1IiIYZ

#  ATIVIDADE 2
"""

import numpy as np
import matplotlib.pyplot as plt

L=1000
d1=L

RY=1500
RX=3000
SY=500
SX=0
ang=np.arctan((RY-SY)/(RX-SX))
x=L*np.tan(ang)
d2=np.sqrt((x)**2+L**2)
d3=np.sqrt(((L/2)-x)**2+(L/2)**2)
x2=(L/2)*np.tan((np.pi/2)-ang )
y=(L-x)*np.tan(ang)
d4=np.sqrt(x2**2+(L/2)**2)
d5=np.sqrt((L-x2)**2+y**2)
d6=np.sqrt(L**2+(L-2*y)**2)
R1=3000
R2=2*d2+d3*2
R3=2*d4+2*d5+d6
print(R1,R2,R3)

G=np.array([[d1,d1,d1,0,0,0,0,0,0],
            [d2,d3,0,0,d3,d2,0,0,0],
            [d4,0,0,d5,d6,d5,0,0,d4],
            [0,d3,d2,d2,d3,0,0,0,0],
            [0,0,0,d1,d1,d1,0,0,0],
            [0,0,0,d2,d3,0,0,d3,d2],
            [0,0,d4,d5,d6,d5,d4,0,0],
            [0,0,0,0,d3,d2,d2,d3,0],
            [0,0,0,0,0,0,d1,d1,d1]])


v=np.loadtxt('V.txt')
vt=v.transpose()
m=np.zeros((9,1))
for i in range (9):
    m[i]=1/vt[i]
t=np.dot(G,m)

print(t.T)

